version: '2'
services:
  influxdb:
    image: "hypriot/rpi-influxdb"
    volumes:
      - ./data/influxdb:/data
    ports:
     - "8086:8086"
    environment:
     - PRE_CREATE_DB="telegraf"

  telegraf:
    image: "arm32v7/telegraf"
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
      - "6514:514/udp"
    links:
      - influxdb

  grafana:
    image: "fg2it/grafana-armhf:v5.1.4"
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=natel-plotly-panel,grafana-simple-json-datasource,natel-discrete-panel
    links:
      - influxdb

volumes:
  grafana-data:
